### ISSUE TITLE
Problem with the REQUIRE

### ISSUE THREAD

**Issue by sherrinm** [JuliaQuant/TradeModels.jl#13]
julia> Pkg.clone("https://github.com/JuliaQuant/TradeModels.jl")
INFO: Cloning TradeModels from https://github.com/JuliaQuant/TradeModels.jl
INFO: Computing changes...
ERROR: unknown package juia required by TradeModels

viz:
juia 0.3-
MarketTechnicals
FinancialBlotter
Reexport

Should be julia NOT juia
Installed manually OK via GIT after  munging the file.

**Comment by milktrader** [comment]
This package is more or less stubbed and has not been fully developed. Eventually it's planned to become part of the entire backtesting toolchain when signals are more complex than technical indicators.
